name: Destroy Azure Infrastructure

on:
  workflow_dispatch:

jobs:
  destroy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Azure Login via OIDC
      uses: azure/login@v1
      with:
        client-id: 'de67da95-4974-4d14-8f84-51c867d76b18'
        tenant-id: '8d768217-7ee4-4314-802d-3d66f76194db'
        subscription-id: '58048bb8-7fbe-431d-b28e-d5bca207fbdf'
 
    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.7.5

    - name: Terraform Init
      run: terraform init

    - name: Terraform Plan Destroy
      run: terraform plan -destroy

    - name: Terraform Destroy
      run: terraform destroy -auto-approve -lock=false
